version: '3.5'

services:
  web:
    restart: always
    build: .
    expose:
      - "5000"
    ports:
      - 5000:5000
    links:
      - dynamodb:dynamodb
    depends_on:
      - dynamodb
    volumes:
      - .:/code/loadlamb
    command: /code/ve/bin/flask run -h 0.0.0.0 -p 5000
    env_file: .env

  dynamodb:
    image: instructure/dynamo-local-admin
    restart: always
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - dynamodata:/var/lib/dynamo

volumes:
  dynamodata:
    driver: local