version: '3.5'

services:
  flask:
    restart: always
    build: .
    expose:
      - "5001"
    ports:
      - 5001:5000
    volumes:
      - .:/code/loadlamb
    command: /root/.cache/pypoetry/virtualenvs/loadlamb-py3.6/bin/flask run -h 0.0.0.0
    env_file: .env
    working_dir: /code/loadlamb/loadlamb/tests/wsgi/flaskr/

  loadlamb:
    restart: always
    build: .
    expose:
      - "7001"
    ports:
      - 7001:7000
    volumes:
      - .:/code/loadlamb
    env_file: .env
    working_dir: /code/loadlamb/loadlamb/loadlambapi/
    command: /root/.cache/pypoetry/virtualenvs/loadlamb-py3.6/bin/chalice local --host 0.0.0.0 --port 7000
  unittest:
    restart: always
    build: .
    volumes:
      - .:/code/loadlamb
    env_file: .env
    working_dir: /code/loadlamb/

  django:
    restart: always
    build: .
    expose:
      - "8001"
    ports:
      - 8001:8001
    volumes:
      - .:/code/loadlamb
    command: /root/.cache/pypoetry/virtualenvs/loadlamb-py3.6/bin/python manage.py runserver 0.0.0.0:8001
    env_file: .env
    working_dir: /code/loadlamb/loadlamb/tests/wsgi/djangor/

  dynamodb:
    image: instructure/dynamo-local-admin
    restart: always
    expose:
      - "8002"
    ports:
      - 8002:8000
    volumes:
      - dynamodata:/var/lib/dynamo

volumes:
  dynamodata:
    driver: local